package com.zarkonnen.spacegen;

import static com.zarkonnen.spacegen.CivAction.*;
import static com.zarkonnen.spacegen.SentientEncounterOutcome.*;


public enum Government {
	DICTATORSHIP(
			"Military Dictatorship",
			"Empire",
			2,
			new SentientEncounterOutcome[] {EXTERMINATE, EXTERMINATE, EXTERMINATE_FAIL, IGNORE, IGNORE, IGNORE, IGNORE, IGNORE, SUBJUGATE, SUBJUGATE, SUBJUGATE, SUBJUGATE, SUBJUGATE, SUBJUGATE},
			EXPLORE_PLANET, EXPLORE_PLANET, COLONISE_PLANET, BUILD_SCIENCE_OUTPOST, BUILD_MINING_BASE, BUILD_MILITARY_BASE, BUILD_MILITARY_BASE, BUILD_MILITARY_BASE, DO_RESEARCH, BUILD_WARSHIPS, BUILD_WARSHIPS, BUILD_WARSHIPS, BUILD_CONSTRUCTION),
	THEOCRACY(
			"Theocracy",
			"Church",
			4,
			new SentientEncounterOutcome[] {EXTERMINATE, EXTERMINATE, EXTERMINATE_FAIL, IGNORE, IGNORE, IGNORE, SUBJUGATE, SUBJUGATE, SUBJUGATE, SUBJUGATE, SUBJUGATE},
			EXPLORE_PLANET, COLONISE_PLANET, COLONISE_PLANET, COLONISE_PLANET, BUILD_MINING_BASE, BUILD_MILITARY_BASE, BUILD_MILITARY_BASE, BUILD_WARSHIPS, BUILD_CONSTRUCTION, BUILD_CONSTRUCTION),
	FEUDAL_STATE(
			"Feudal State",
			"Kingdom",
			2,
			new SentientEncounterOutcome[] {EXTERMINATE, EXTERMINATE_FAIL, IGNORE, IGNORE, IGNORE, IGNORE, IGNORE, SUBJUGATE, SUBJUGATE, SUBJUGATE, GIVE_FULL_MEMBERSHIP},
			EXPLORE_PLANET, COLONISE_PLANET, COLONISE_PLANET, BUILD_MINING_BASE, BUILD_MILITARY_BASE, DO_RESEARCH, BUILD_WARSHIPS, BUILD_WARSHIPS, BUILD_CONSTRUCTION),
	REPUBLIC(
			"Republic",
			"Republic",
			1,
			new SentientEncounterOutcome[] {EXTERMINATE, EXTERMINATE, EXTERMINATE_FAIL, IGNORE, IGNORE, IGNORE, IGNORE, IGNORE, SUBJUGATE, SUBJUGATE, GIVE_FULL_MEMBERSHIP, GIVE_FULL_MEMBERSHIP, GIVE_FULL_MEMBERSHIP, GIVE_FULL_MEMBERSHIP, GIVE_FULL_MEMBERSHIP, GIVE_FULL_MEMBERSHIP, GIVE_FULL_MEMBERSHIP},
			EXPLORE_PLANET, COLONISE_PLANET, BUILD_MINING_BASE, BUILD_MINING_BASE, BUILD_MILITARY_BASE, BUILD_SCIENCE_OUTPOST, DO_RESEARCH, BUILD_WARSHIPS, BUILD_CONSTRUCTION, BUILD_CONSTRUCTION);
	
	final String typeName;
	final String title;
	final int bombardP;
	final CivAction[] behaviour;
	SentientEncounterOutcome[] encounterOutcomes;

	private Government(String name, String title, int bombardP, SentientEncounterOutcome[] encounterOutcomes, CivAction... behaviour) {
		this.typeName = name;
		this.behaviour = behaviour;
		this.title = title;
		this.bombardP = bombardP;
		this.encounterOutcomes = encounterOutcomes;
	}
	
	
}
